blueprint:
  name: Microwave Indicator
  description: >
    Shows a red light when microwave is cooking and green light when done.
  domain: automation
  input:
    power_sensor:
      name: Power Sensor
      description: The power sensor that measures the microwave’s power usage in watts.
      selector:
        entity:
          domain: sensor
    red_entity:
      name: Red Indicator
      description: Entity (light or switch) that turns on while cooking.
      selector:
        entity:
          domain: [light, switch]
    green_entity:
      name: Green Indicator
      description: Entity (light or switch) that turns on when cooking ends.
      selector:
        entity:
          domain: [light, switch]
    on_threshold:
      name: On Threshold
      description: Wattage above which microwave is considered “on”.
      default: 10
      selector:
        number:
          min: 1
          max: 3000
          unit_of_measurement: W
          mode: box
    off_threshold:
      name: Off Threshold
      description: Wattage below which microwave is considered “off”.
      default: 10
      selector:
        number:
          min: 0
          max: 3000
          unit_of_measurement: W
          mode: box
    green_on_duration:
      name: Green On Duration
      description: How long the green indicator stays on after cooking ends.
      default: 60
      selector:
        number:
          min: 5
          max: 300
          unit_of_measurement: seconds
          mode: box
